/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Activate
 #	author : miyako
 #	2016/09/29
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include "Shlwapi.h"
#endif

// --- Activate
void ACTIVATE_4D(sLONG_PTR *pResult, PackagePtr pParams);

HWND GetMainHWND();