/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-activate.h
 #	source generated by 4D Plugin Wizard
 #	Project : activate
 #	author : miyako
 #	2020/02/14
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ACTIVATE_H
#define PLUGIN_ACTIVATE_H

#include "4DPluginAPI.h"

#if VERSIONMAC
#include <Cocoa/Cocoa.h>
#endif

#if VERSIONWIN
#include "windows.h"
#endif

#pragma mark -

void ACTIVATE_4D(PA_PluginParameters params);

#endif /* PLUGIN_ACTIVATE_H */
