/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-activate.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : activate
 #	author : miyako
 #	2020/02/14
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-activate.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
    try
    {
        switch(selector)
        {
        
                // --- activate
                
            case 1 :
                ACTIVATE_4D(params);
                break;
                
        }
        
    }
    catch(...)
    {
        
    }
}

#pragma mark -

#if VERSIONWIN
void activate_window(HWND m_hWnd) {
	/*
	https://stackoverflow.com/questions/916259/win32-bring-a-window-to-top
	*/
	HWND hCurWnd = ::GetForegroundWindow();
	DWORD dwMyID = ::GetCurrentThreadId();
	DWORD dwCurID = ::GetWindowThreadProcessId(hCurWnd, NULL);
	::AttachThreadInput(dwCurID, dwMyID, TRUE);
	//::ShowWindowAsync(m_hWnd, SW_RESTORE);
	::ShowWindow(m_hWnd, SW_RESTORE);
	::SetWindowPos(m_hWnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE);
	::SetWindowPos(m_hWnd, HWND_NOTOPMOST, 0, 0, 0, 0, SWP_SHOWWINDOW | SWP_NOSIZE | SWP_NOMOVE);
	::SetForegroundWindow(m_hWnd);
	::SetFocus(m_hWnd);
	::SetActiveWindow(m_hWnd);
	::AttachThreadInput(dwCurID, dwMyID, FALSE);
}
#endif

void ACTIVATE_4D(PA_PluginParameters params) {
    
#if VERSIONMAC
    [[NSRunningApplication currentApplication]activateWithOptions:NSApplicationActivateIgnoringOtherApps];
#endif
    
#if VERSIONWIN
    
	PA_Variable args[5];

	args[0] = PA_CreateVariable(eVK_Longint);
	args[1] = PA_CreateVariable(eVK_Longint);
	args[2] = PA_CreateVariable(eVK_Longint);
	args[3] = PA_CreateVariable(eVK_Longint);
	args[4] = PA_CreateVariable(eVK_Longint);
	PA_SetLongintVariable(&args[4], (PA_long32)-1);

	PA_ExecuteCommandByID(443 /*GET WINDOW RECT*/, args, 5);

	bool isSDI = (PA_GetLongintVariable(args[0]) == 0) 
		&& (PA_GetLongintVariable(args[1]) == 0)
		&& (PA_GetLongintVariable(args[2]) == 0)
		&& (PA_GetLongintVariable(args[3]) == 0);

	if(!isSDI) {
		PA_RunInMainProcess((PA_RunInMainProcessProcPtr)activate_window, (HWND)PA_GetMainWindowHWND());
	}

	PA_long32 arg1 = PA_GetLongParameter(params, 1);

	if (arg1 == 0) {
		args[4] = PA_ExecuteCommandByID(827 /*Current form window*/, args, 0);
		arg1 = PA_GetLongintVariable(args[4]);
	}

	PA_WindowRef l = (PA_WindowRef)arg1;

	if (l) {
		sLONG_PTR w = PA_GetHWND(l);
		if (w) {
			PA_RunInMainProcess((PA_RunInMainProcessProcPtr)activate_window, (HWND)w);
		}
	}
#endif
}
